config/routes.rb
Rails.application.routes.draw do
  resources :log_events
  devise_for :teachers
  root to: 'log_events#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/log_event.rb
class LogEvent < ApplicationRecord
  belongs_to :teacher

  enum event_type: {
    check_in: 'check in',
    check_out: 'check out',
  }

  validates_presence_of :event_time, :event_type
  validate :previous_event_conflict
  validate :first_event_is_check_in

  scope :order_by_latest, -> { order(event_time: :desc) }
  scope :for_teacher, ->(teacher) { where(teacher: teacher) }
  scope :events_during, -> (start_time, end_time) {
    where(event_time: start_time..end_time)
  }

  def previous_event_for_the_day
    start_at = event_time.beginning_of_day
    end_at = event_time - 1.second
    LogEvent.for_teacher(teacher)
      .events_during(start_at, end_at)
      .order_by_latest
      .first
  end

  private

  # Validations
  def previous_event_conflict
    if previous_event_for_the_day&.event_type == event_type
      errors.add(:event_type, "Please check the Event type: #{event_type} \
                 as the previous event was #{event_type} as well")
    end
  end

  def first_event_is_check_in
    if previous_event_for_the_day.nil? && event_type != 'check_in'
      day = event_time.strftime('%A, %b %d')
      errors.add(:event_type, "The first event for the day #{day} \
                 is not allowed to be check out")
    end
  end
end

app/models/teacher.rb
class Teacher < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :log_events
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_teacher!
end

app/controllers/log_events_controller.rb
class LogEventsController < ApplicationController
  before_action :set_log_event, only: [:show, :edit, :update, :destroy]

  # GET /log_events
  # GET /log_events.json
  def index
    @log_events = LogEvent.for_teacher(current_teacher).order_by_latest
  end

  # GET /log_events/1
  # GET /log_events/1.json
  def show
  end

  # GET /log_events/new
  def new
    @log_event = LogEvent.new
  end

  # GET /log_events/1/edit
  def edit
  end

  # POST /log_events
  # POST /log_events.json
  def create
    @log_event = LogEvent.new(log_event_params)
    @log_event.teacher = current_teacher

    respond_to do |format|
      if @log_event.save
        format.html { redirect_to @log_event, notice: 'Log event was successfully created.' }
        format.json { render :show, status: :created, location: @log_event }
      else
        format.html { render :new }
        format.json { render json: @log_event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /log_events/1
  # PATCH/PUT /log_events/1.json
  def update
    respond_to do |format|
      if @log_event.update(log_event_params)
        format.html { redirect_to @log_event, notice: 'Log event was successfully updated.' }
        format.json { render :show, status: :ok, location: @log_event }
      else
        format.html { render :edit }
        format.json { render json: @log_event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /log_events/1
  # DELETE /log_events/1.json
  def destroy
    @log_event.destroy
    respond_to do |format|
      format.html { redirect_to log_events_url, notice: 'Log event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_log_event
      @log_event = LogEvent.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def log_event_params
      params.require(:log_event).permit(:event_time, :description, :event_type)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/log_events_helper.rb
module LogEventsHelper
  def event_types_to_select
    LogEvent.event_types.map { |key, value| [value, key] }
  end

  def format_event_time(time)
    time.to_s(:short)
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TeacherApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/log_events/_form.html.erb
<%= form_for(log_event) do |f| %>
  <% if log_event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(log_event.errors.count, "error") %> prohibited this log_event from being saved:</h2>

      <ul>
      <% log_event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :event_time %>
    <%= f.datetime_select :event_time %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>

  <div class="field">
    <%= f.label :event_type %>
    <%= f.select :event_type, event_types_to_select %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/log_events/edit.html.erb
<h1>Editing Log Event</h1>

<%= render 'form', log_event: @log_event %>

<%= link_to 'Show', @log_event %> |
<%= link_to 'Back', log_events_path %>

app/views/log_events/index.html.erb
<p id="notice"><%= notice %></p>

<h1><%= "Welcome #{current_teacher.email}" %></h1>

<table>
  <thead>
    <tr>
      <th>Event time</th>
      <th>Description</th>
      <th>Event type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @log_events.each do |log_event| %>
      <tr>
        <td><%= format_event_time(log_event.event_time) %></td>
        <td><%= log_event.description %></td>
        <td><%= log_event.event_type %></td>
        <td><%= link_to 'Show', log_event %></td>
        <td><%= link_to 'Edit', edit_log_event_path(log_event) %></td>
        <td><%= link_to 'Destroy', log_event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Log Event', new_log_event_path %>

app/views/log_events/new.html.erb
<h1>New Log Event</h1>

<%= render 'form', log_event: @log_event %>

<%= link_to 'Back', log_events_path %>

app/views/log_events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Teacher:</strong>
  <%= @log_event.teacher %>
</p>

<p>
  <strong>Event time:</strong>
  <%= @log_event.event_time %>
</p>

<p>
  <strong>Description:</strong>
  <%= @log_event.description %>
</p>

<p>
  <strong>Event type:</strong>
  <%= @log_event.event_type %>
</p>

<%= link_to 'Edit', edit_log_event_path(@log_event) %> |
<%= link_to 'Back', log_events_path %>